MODEL:
  SESSION: "Paxton"

PROJECT:
  ROOT_PATH: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/
  TRAIN_DIR: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/dataset/LSUI19/Train
  VAL_DIR: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/dataset/LSUI19/Val
  SAVE_DIR: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/save_dir
  EXPT_RECORD_DIR: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/expt_record
  LOG_DIR: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/log
  VISUAL_DATA: /public/home/hnust15874739861/pro/UnderwaterImageEnhanced/dataset/visual_img


DATASET:
  INPUT: 'input'
  TARGET: 'GT'

TRAIN:
  DEVICE: 'cuda:2'
  VAL_AFTER_EVERY: 1
  RESUME: False
  WEIGHT: ''
  IMG_H: 256
  IMG_W: 256
  ORI: False
  BATCH_SIZE: 32
  LR: 2e-4
  EPOCHS: 500
  PRINT_FREQ: 1



